// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChelXhkknS4bmO9Af4PVk7WrymeTJEuKo',
    appId: '1:631736958664:web:c22b842843f4b0350eaffd',
    messagingSenderId: '631736958664',
    projectId: 'agora-hci-2025',
    authDomain: 'agora-hci-2025.firebaseapp.com',
    storageBucket: 'agora-hci-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe5PcKP6ExPrCo3EM5uDWAl6ewVEFkIHM',
    appId: '1:631736958664:android:a2d30a491657dd640eaffd',
    messagingSenderId: '631736958664',
    projectId: 'agora-hci-2025',
    storageBucket: 'agora-hci-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3LluarLFxUnBI73-tFX4o0BzwGNbuYsw',
    appId: '1:631736958664:ios:ef62323ad7a597fd0eaffd',
    messagingSenderId: '631736958664',
    projectId: 'agora-hci-2025',
    storageBucket: 'agora-hci-2025.firebasestorage.app',
    iosBundleId: 'com.example.agora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3LluarLFxUnBI73-tFX4o0BzwGNbuYsw',
    appId: '1:631736958664:ios:ef62323ad7a597fd0eaffd',
    messagingSenderId: '631736958664',
    projectId: 'agora-hci-2025',
    storageBucket: 'agora-hci-2025.firebasestorage.app',
    iosBundleId: 'com.example.agora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChelXhkknS4bmO9Af4PVk7WrymeTJEuKo',
    appId: '1:631736958664:web:91ad5bcaf82799e30eaffd',
    messagingSenderId: '631736958664',
    projectId: 'agora-hci-2025',
    authDomain: 'agora-hci-2025.firebaseapp.com',
    storageBucket: 'agora-hci-2025.firebasestorage.app',
  );
}
